# Generated by Django 6.0 on 2026-01-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
